---
- name: Retrive user's default shell
  shell: dscl . -read /Users/{{ target_user_id }} UserShell | sed 's/ //g' | cut -d ':' -f2
  register: command_result

- debug:
    msg: "{{ command_result }}"
  when: verbose | bool

- name: User's default shell
  set_fact:
    user_default_shell: "{{ item  }}"
  loop:
    - "{{ command_result.stdout | basename }}"

- name: Set 'HOMEBREW_AUTO_UPDATE_SECS' in the user's {{ user_default_shell }} config
  lineinfile:
    path: "{{ item.config_file }}"
    state: present
    regexp: '^.*HOMEBREW_AUTO_UPDATE_SECS.*$'
    line: "{{ item.line }}"
    create: yes
  loop:
    - shell: 'bash'
      config_file: "/Users/{{ target_user_id }}/.bashrc"
      line: "export HOMEBREW_AUTO_UPDATE_SECS='{{ homebrew_auto_update_tollerance }}'"

    - shell: 'zsh'
      config_file: "/Users/{{ target_user_id }}/.zshrc"
      line: "export HOMEBREW_AUTO_UPDATE_SECS='{{ homebrew_auto_update_tollerance }}'"

    - shell: 'fish'
      config_file: "/Users/{{ target_user_id }}/.config/fish/config.fish"
      line: "set -gx HOMEBREW_AUTO_UPDATE_SECS '{{ homebrew_auto_update_tollerance }}'"
  when: item.shell == user_default_shell or homebrew_auto_update_for_all_shell_types|bool
...
